import Head from 'next/head';

import ProductList from '../src/components/product/ProductList';

export default function Home() {
	return (
		<>
			<Head>
				<title>Ecommerce Prodcut UI</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<ProductList />
			</main>
		</>
	);
}
